export const TEST_PRIVATE_KEY = process.env.TEST_PRIVATE_KEY;
export const ETHERSCAN_API_KEY = process.env.ETHERSCAN_API_KEY;
export const POLYGONSCAN_API_KEY = process.env.POLYGONSCAN_API_KEY;
export const BSCSCAN_API_KEY = process.env.BSCSCAN_API_KEY;
export const SNOWTRACE_API_KEY = process.env.SNOWTRACE_API_KEY;
export const COINGECKO_API_KEY = process.env.COINGECKO_API_KEY;
export const NODE_ENV = process.env.NODE_ENV;
export const STARGAZER_SWAPPING_BASE_URL_PROD =
  process.env.STARGAZER_SWAPPING_BASE_URL_PROD;
export const STARGAZER_PROVIDERS_BASE_URL = process.env.STARGAZER_PROVIDERS_BASE_URL;
export const STARGAZER_PROVIDERS_BASE_URL_PROD =
  process.env.STARGAZER_PROVIDERS_BASE_URL_PROD;
export const STARGAZER_API_KEY = process.env.STARGAZER_API_KEY;
export const QUICKNODE_ETHEREUM_MAINNET = process.env.QUICKNODE_ETHEREUM_MAINNET;
export const QUICKNODE_ETHEREUM_SEPOLIA = process.env.QUICKNODE_ETHEREUM_SEPOLIA;
export const QUICKNODE_POLYGON_MAINNET = process.env.QUICKNODE_POLYGON_MAINNET;
export const QUICKNODE_POLYGON_TESTNET = process.env.QUICKNODE_POLYGON_TESTNET;
export const QUICKNODE_BSC_MAINNET = process.env.QUICKNODE_BSC_MAINNET;
export const QUICKNODE_BSC_TESTNET = process.env.QUICKNODE_BSC_TESTNET;
export const QUICKNODE_AVALANCHE_MAINNET = process.env.QUICKNODE_AVALANCHE_MAINNET;
export const QUICKNODE_AVALANCHE_TESTNET = process.env.QUICKNODE_AVALANCHE_TESTNET;
export const isProd = NODE_ENV === 'production';
export const isNative = false;
