import { StyleSheet } from 'react-native';
import { COLORS, FONTS } from 'assets/styles/_variables';

const styles = StyleSheet.create({
  fullselect: {
    position: 'relative',
    width: '100%',
    display: 'flex',
    alignItems: 'center',
    textAlign: 'center',
    flexDirection: 'column',
    height: 60,
    transition: 'all 300ms',
  },
  selected: {
    width: '100%',
    height: 36,
    marginTop: 12,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
  },
  selectedMain: {
    display: 'flex',
    flexDirection: 'row',
    transition: 'all 0.3s',
    alignItems: 'center',
  },
  assetLogo: {
    marginRight: 8,
  },
  address: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    height: 60,
    width: '100%',
    // font-family: FONTS.quicksand,
    fontWeight: 'bold',
    fontSize: 18,
    lineHeight: 24,
    color: COLORS.white,
    transition: 'all 0.3s',
    cursor: 'pointer',
  },
  addressActive: {
    color: COLORS.gray_light,
  },
  addressText: {
    fontSize: 12,
    lineHeight: 10,
    fontWeight: 500,
    // fontFamily: FONTS.quicksand,
    marginTop: 2,
    marginLeft: 0,
    color: COLORS.white,
    transition: 'all 0.3s',
  },
  options: {
    margin: 0,
    padding: 0,
    // listStyle: none,
    transition: 'all 300ms',
    // transform: 'scaleY(0)',
    transformOrigin: 'top',
    position: 'absolute',
    width: '100%',
    top: 60,
    background: 'rgba($white, 0.8)',
    backdropFilter: 'blur(10)',
    borderBottomColor: COLORS.gray_dark,
    borderWidth: 1,
    overflow: 'scroll',
    maxHeight: 468,
    zIndex: 10,
  },
});

export default styles;
