import { StyleSheet } from 'react-native';
import { COLORS } from 'assets/styles/_variables';

const styles = StyleSheet.create({
  wrapper: {
    flex: 1,
    flexDirection: 'column',
    width: '100%',
    backgroundColor: COLORS.primary,
  },
  mask: {
    flexGrow: 1,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.primary,
    opacity: 1,
  },
  loaderHide: {
    opacity: 0,
  },
  network: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 16,
  },
  logoContainer: {
    height: 24,
    width: 24,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 12,
    marginRight: 8,
  },
  logo: {
    height: 24,
    width: 24,
  },
  account: {
    height: 60,
    width: '100%',
    marginTop: 72,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 3,
  },
  accountText: {
    fontWeight: 'bold',
    fontSize: 18,
    lineHeight: 24,
    display: 'flex',
    alignItems: 'center',
    textAlign: 'center',
    color: COLORS.dark_gray,
  },
  accountTextSmall: {
    fontWeight: '600',
    fontSize: 12,
    textAlign: 'center',
    letterSpacing: 0.03,
    lineHeight: 24,
    color: COLORS.gray,
    position: 'relative',
  },
  copy: {
    position: 'absolute',
    right: -38,
    bottom: 1,
    width: 24,
    height: 24,
  },
  copyIcon: {
    height: 18,
    width: 'auto',
  },
  center: {
    width: '100%',
    display: 'flex',
    alignItems: 'center',
    flexDirection: 'column',
    position: 'relative',
    paddingTop: 24,
  },
  balance: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
  },
  balanceText: {
    maxWidth: 200,
    overflow: 'hidden',
    marginRight: 8,
  },
  symbolText: {
    fontSize: 20,
    lineHeight: 28,
  },
  fiatBalance: {
    marginTop: 8,
  },
  fiatText: {
    fontSize: 16,
    lineHeight: 24,
    color: 'rgba(255, 255, 255, 0.66)',
  },
  actions: {
    width: '100%',
    flexDirection: 'row',
    marginBottom: 24,
    marginTop: 32,
  },
  activity: {
    backgroundColor: COLORS.gray_light,
    width: '100%',
    height: 2000,
    display: 'flex',
    flexDirection: 'column',
  },
  spinner: {
    color: COLORS.primary,
  },
  stargazer: {
    bottom: 0,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
    opacity: 0.6,
  },
  noTx: {
    display: 'flex',
    flex: 1,
    margin: 20,
  },
  heading: {
    display: 'flex',
    backgroundColor: COLORS.gray_light,
    borderWidth: 1,
    borderBottomColor: COLORS.gray_100,
    top: 0,
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    fontWeight: 'bold',
    fontSize: 18,
    lineHeight: 60,
    width: '100%',
    color: COLORS.gray_dark,
    zIndex: 2,
  },
  goTop: {
    width: 26,
    fontSize: 16,
    height: 26,
    position: 'absolute',
    right: 36,
  },
  ul: {
    margin: 0,
    padding: 0,
    width: '100%',
    position: 'relative',
    zIndex: 1,
    flexGrow: 4,
  },
  li: {
    width: '100%',
    height: 84,
    display: 'flex',
    flexDirection: 'row',
    paddingVertical: 0,
    paddingHorizontal: 36,
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  hover: {
    backgroundColor: `rgab(${COLORS.gray_light_100}, 0.9)`,
  },
  hoverLinkIcon: {
    backgroundColor: COLORS.gray_200,
  },
  groupbar: {
    height: 24,
    backgroundColor: COLORS.purple_medium,
    fontWeight: '500',
    fontSize: 12,
    lineHeight: 18,
    color: COLORS.purple,
  },
  groupBarDiv: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  firstChild: {
    fontSize: 16,
  },
  groupBarText: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
    fontWeight: '500',
    fontSize: 18,
    lineHeight: 24,
    color: COLORS.gray_dark,
  },
  groupBarSpan: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'flex-end',
  },
  groupBarTextSpan: {
    fontWeight: '500',
    fontSize: 12,
    lineHeight: 18,
    marginLeft: 4,
  },
  small: {
    marginTop: 4,
    fontWeight: '500',
    fontSize: 12,
    lineHeight: 18,
    color: COLORS.gray,
    width: 96,
    textAlign: 'right',
  },
  lastChild: {
    alignItems: 'flex-end',
    justifyContent: 'flex-end',
  },
  bullet: {
    height: 16,
    width: 'auto',
    marginRight: 12,
    color: COLORS.purple,
  },
  angle: {
    height: 25,
    marginLeft: 12,
    color: COLORS.gray_medium,
  },
  iconWrapper: {
    width: 24,
    height: 24,
    backgroundColor: 'transparent',
    borderRadius: 50,
    color: COLORS.gray_100,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  icon: {
    fontSize: 16,
  },
  recvIcon: {},
  linkIcon: {
    width: 24,
    height: 24,
    backgroundColor: 'transparent',
    borderRadius: 50,
    color: COLORS.gray_dark,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 12,
    // transition: 'all 0.3s',
  },
  assets: {
    width: '100%',
  },
  assetList: {
    margin: 0,
    padding: 0,
    width: '100%',
    position: 'relative',
    zIndex: 1,
    flexGrow: 4,
  },
  assetItem: {
    width: '100%',
    height: 10,
    display: 'flex',
    flexDirection: 'row',
    paddingTop: 0,
    paddingRight: 36,
    paddingBottom: 0,
    paddingLeft: 37,
    alignItems: 'center',
    justifyContent: 'space-between',
    borderBottomColor: COLORS.white,
    borderWidth: 1,
  },
  qrCode: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  qrCodeCard: {
    backgroundColor: 'white',
    padding: 20,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  qrCodeCloseButton: {
    alignItems: 'flex-end',
    marginRight: 20,
    marginTop: 20,
  },
  qrCodeAddressText: {
    marginRight: 12,
  },
  addressContainer: {
    marginTop: 20,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  tabLabel: {
    fontWeight: '500',
    lineHeight: 24,
    marginLeft: 8,
  },
  labelFocused: {
    fontWeight: '600',
    lineHeight: 24,
  },
  labelContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  tabBar: {
    backgroundColor: COLORS.primary,
    height: 50,
  },
  tabBarLabel: {
    color: COLORS.gray_300,
  },
  tabBarIndicator: {
    backgroundColor: '#7070FF',
    height: 6,
  },
});

export default styles;
