export { default as MainView } from './MainView';
export { default as WalletsView } from './WalletsView';
export { default as AddWalletView } from './AddWalletView';
export { default as ImportWalletView } from './ImportWalletView';
export { default as NetworksView } from './NetworksView';
export { default as ManageWalletView } from './ManageWalletView';
export { default as ImportPhraseView } from './ImportPhraseView';
// export { default as AccountView } from './AccountView';
// export { default as GeneralView } from './GeneralView';
export { default as PhraseView } from './PhraseView';
// export { default as DeleteWalletView } from './DeleteWalletView';
export { default as RemoveWalletView } from './RemoveWalletView';
export { default as PrivateKeyView } from './PrivateKeyView';
export { default as NewAccountView } from './NewAccountView';
export { default as AboutView } from '../AboutView';
export { default as ContactsView } from './ContactsView';
export { default as ContactView } from './ContactInfoView';
export { default as ModifyContactView } from './ModifyContactView';
export { default as ImportAccountView } from './ImportAccountView';
