export const DEPOSIT_ADDRESS_STRING = 'Deposit Address';
export const SWAP_FROM_STRING = 'Swap from';
export const SWAP_TO_STRING = 'Swap to';
export const TRANSACTION_FEE_STRING = 'Transaction Fee';
export const RECOMMENDED_STRING = 'Recommended';
export const NEXT_BUTTON_STRING = 'Next';
export const GAS_PRICE_IN_GWEI_STRING = 'Gas Price (in GWEI)'
export const DAG_CODE = 'DAG';
export const GAS_SLIDER_STEP = 1;
export const TRANSACTION_FEE_DEFAULT_VALUE = '0';
export const ACTIVITY_INDICATOR_COLOR = '#473194';